### ISSUE TITLE
Error with lock on /var/lib/dpkg

### ISSUE THREAD

**Issue by thomsonjames** [nmenant/f5-101-lab-Mesos-Marathon#22]
I launched the UDF blue print and went to run the first step of "sudo apt-get update" and get the following:

user@mesos:~/github_repo/101-lab-Mesos-Marathon/ansible/playbooks$ sudo apt-get                                                                update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Fetched 306 kB in 6s (50.7 kB/s)
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
user@mesos:~/github_repo/101-lab-Mesos-Marathon/ansible/playbooks$

I deleted and recreated the instance a few times.
I tried running the ansible scripts instead, but nothing seems to solve.

**Comment by nmenant** [comment]
Yes it means that you have an instance of apt that is already running or failed in between and didn't remove the lock on apt. 
Try the following:

sudo rm /var/lib/dpkg/lock
sudo dpkg --configure -a

Once you've done this. Try  : 

sudo apt-get update and see if it works. If it does, you should be able to run the the solution after that

**Comment by thomsonjames** [comment]
That worked. Not sure how I did that on my first try.
